---

 - hosts: all
   become: true
   tasks:

   - name: udapte and upgrade ubuntu
     tags: always
     apt: 
       update_cache: yes
       upgrade: dist
     when: ansible_distribution == "Ubuntu"

   - name: update and upgrade centos
     tags: always
     yum:
       update_only: yes
       name: "*"
       state: latest
     when: ansible_distribution == "CentOS"

